import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
df = pd.read_csv("911.csv")
df.info()
df.head()
df['zip'].value_counts().head(5)
df['twp'].value_counts().head(5)
df['title'].nunique()

x = df['title'].iloc[0]
x.split(':')[0]
df['Reason'] = df['title'].apply(lambda title: title.split(':')[0])
df['Reason']
df['Reason'].value_counts()
sns.countplot(x='Reason',data = df,palette ='viridis')

type(df['timeStamp'].iloc[0])
df['timeStamp'] = pd.to_datetime(df['timeStamp'])
df['Hour'] = df['timeStamp'].apply(lambda time: time.hour)
df['Hour']
df['Month'] = df['timeStamp'].apply(lambda time: time.month)
df['Month']
df['Day of Week'] = df['timeStamp'].apply(lambda time: time.dayofweek)
df['Day of Week']

dmap = {0:'Mon',1:'Tue',2:'Wed',3:'Thu',4:'Fri',5:'Sat',6:'Sun'}
df['Day of Week'] = df['Day of Week'].map(dmap)
df.head()

sns.countplot(x = 'Day of Week', data = df , hue = 'Reason',palette = 'viridis')
plt.legend(bbox_to_anchor=(1.05,1),loc= 2,borderaxespad=0)

sns.countplot(x = 'Month', data = df , hue = 'Reason',palette = 'viridis')
plt.legend(bbox_to_anchor=(1.05,1),loc= 2,borderaxespad=0)

byMonth = df.groupby('Month').count()
byMonth

byMonth['lat'].plot()

sns.countplot(x = 'Month', data = df ,palette = 'viridis')
plt.legend(bbox_to_anchor=(1.05,1),loc= 2,borderaxespad=0)

byMonth.reset_index()
sns.lmplot(x='Month',y='twp',data=byMonth.reset_index())

t=df['timeStamp'].iloc[0]
df['Date'] = df['timeStamp'].apply(lambda t:t.date())
df.head()

df.groupby('Date').count()['lat'].plot()
plt.tight_layout()

df[df['Reason']=='Traffic'].groupby('Date').count()['lat'].plot()
plt.title('Traffic')
plt.tight_layout()

df[df['Reason']=='Fire'].groupby('Date').count()['lat'].plot()
plt.title('Fire')
plt.tight_layout()

df[df['Reason']=='EMS'].groupby('Date').count()['lat'].plot()
plt.title('EMS')
plt.tight_layout()


dayHour=df.groupby(['Day of Week', 'Hour']).count()['Reason'].unstack()

plt.figure(figsize= (12,6))
sns.heatmap(dayHour,cmap='viridis')

sns.clustermap(dayHour,cmap='viridis')



dayMonth=df.groupby(['Day of Week', 'Month']).count()['Reason'].unstack()

plt.figure(figsize=(12,6))
sns.heatmap(dayMonth,cmap= 'viridis')

plt.figure(figsize=(12,6))
sns.clustermap(dayMonth,cmap= 'viridis')

